const LEARNABLE_MOVES = {
  '阿柏蛇': [
    { level: 1, name: '撞击' },
    { level: 5, name: '瞪眼' },
    { level: 9, name: '毒针' },
    { level: 13, name: '摇尾巴' },
    { level: 17, name: '缠绕' },
    { level: 21, name: '毒牙' },
    { level: 25, name: '击掌奇袭' },
    { level: 29, name: '毒尾' },
    { level: 33, name: '污泥炸弹' },
    { level: 37, name: '剧毒' },
    { level: 41, name: '咬碎' }
  ],
  '阿柏怪': [
    { level: 1, name: '撞击' },
    { level: 1, name: '毒针' },
    { level: 1, name: '缠绕' },
    { level: 1, name: '瞪眼' },
    { level: 4, name: '撞击' },
    { level: 9, name: '毒针' },
    { level: 13, name: '摇尾巴' },
    { level: 17, name: '缠绕' },
    { level: 21, name: '毒牙' },
    { level: 25, name: '击掌奇袭' },
    { level: 29, name: '毒尾' },
    { level: 33, name: '污泥炸弹' },
    { level: 37, name: '剧毒' },
    { level: 43, name: '黑色目光' },
    { level: 47, name: '咬碎' }
  ],
  '瓦斯弹': [
    { level: 1, name: '撞击' },
    { level: 4, name: '毒烟' },
    { level: 8, name: '毒针' },
    { level: 12, name: '烟幕' },
    { level: 15, name: '毒液冲击' },
    { level: 19, name: '吼叫' },
    { level: 22, name: '剧毒' },
    { level: 26, name: '自爆' },
    { level: 30, name: '污泥炸弹' },
    { level: 34, name: '爆炸' }
  ],
  '超音蝠': [
    { level: 1, name: '撞击' },
    { level: 5, name: '超音波' },
    { level: 9, name: '吸血' },
    { level: 13, name: '翅膀攻击' },
    { level: 17, name: '咬咬' },
    { level: 21, name: '空气切割' },
    { level: 25, name: '十字毒牙' },
    { level: 29, name: '勇鸟猛攻' },
    { level: 33, name: '影子球' }
  ],
  '大嘴蝠': [
    { level: 1, name: '撞击' },
    { level: 1, name: '翅膀攻击' },
    { level: 1, name: '吸血' },
    { level: 1, name: '超音波' },
    { level: 5, name: '超音波' },
    { level: 9, name: '吸血' },
    { level: 13, name: '翅膀攻击' },
    { level: 17, name: '咬咬' },
    { level: 21, name: '空气切割' },
    { level: 25, name: '十字毒牙' },
    { level: 29, name: '勇鸟猛攻' },
    { level: 33, name: '影子球' },
    { level: 37, name: '神鸟猛击' }
  ],
  '波波': [
    { level: 1, name: '撞击' },
    { level: 5, name: '沙鳞' },
    { level: 9, name: '翅膀攻击' },
    { level: 13, name: '高速移动' },
    { level: 17, name: '电光一闪' },
    { level: 21, name: '啄' },
    { level: 25, name: '空气刃' },
    { level: 29, name: '神鸟猛击' }
  ],
  '比比鸟': [
    { level: 1, name: '撞击' },
    { level: 1, name: '翅膀攻击' },
    { level: 1, name: '啄' },
    { level: 1, name: '高速移动' },
    { level: 5, name: '沙鳞' },
    { level: 9, name: '翅膀攻击' },
    { level: 13, name: '高速移动' },
    { level: 17, name: '电光一闪' },
    { level: 21, name: '啄' },
    { level: 25, name: '空气刃' },
    { level: 29, name: '钢翼' },
    { level: 33, name: '神鸟猛击' },
    { level: 37, name: '勇鸟猛攻' }
  ],
  '大比鸟': [
    { level: 1, name: '翅膀攻击' },
    { level: 1, name: '飞翔' },
    { level: 1, name: '高速移动' },
    { level: 1, name: '神鸟猛击' },
    { level: 5, name: '沙鳞' },
    { level: 9, name: '翅膀攻击' },
    { level: 13, name: '高速移动' },
    { level: 17, name: '电光一闪' },
    { level: 21, name: '啄' },
    { level: 25, name: '空气刃' },
    { level: 29, name: '钢翼' },
    { level: 33, name: '神鸟猛击' },
    { level: 37, name: '勇鸟猛攻' },
    { level: 42, name: '破坏死光' }
  ],
  '小拉达': [
    { level: 1, name: '撞击' },
    { level: 4, name: '摇尾巴' },
    { level: 7, name: '电光一闪' },
    { level: 10, name: '必杀门牙' },
    { level: 13, name: '愤怒' },
    { level: 16, name: '追击' },
    { level: 19, name: '高速星星' },
    { level: 22, name: '疯狂乱抓' },
    { level: 25, name: '咬碎' }
  ],
  '拉达': [
    { level: 1, name: '撞击' },
    { level: 1, name: '电光一闪' },
    { level: 1, name: '必杀门牙' },
    { level: 1, name: '愤怒' },
    { level: 4, name: '摇尾巴' },
    { level: 7, name: '电光一闪' },
    { level: 10, name: '必杀门牙' },
    { level: 13, name: '愤怒' },
    { level: 16, name: '追击' },
    { level: 19, name: '高速星星' },
    { level: 22, name: '疯狂乱抓' },
    { level: 25, name: '咬碎' },
    { level: 28, name: '舍身冲撞' },
    { level: 31, name: '破坏死光' }
  ],
  '烈雀': [
    { level: 1, name: '撞击' },
    { level: 5, name: '啄' },
    { level: 9, name: '叫声' },
    { level: 13, name: '追击' },
    { level: 17, name: '电光一闪' },
    { level: 21, name: '空气刃' },
    { level: 25, name: '神鸟猛击' },
    { level: 29, name: '破坏死光' }
  ],
  '大嘴雀': [
    { level: 1, name: '啄' },
    { level: 1, name: '翅膀攻击' },
    { level: 1, name: '尖嘴攻击' },
    { level: 1, name: '勇鸟猛攻' },
    { level: 5, name: '啄' },
    { level: 9, name: '叫声' },
    { level: 13, name: '追击' },
    { level: 17, name: '电光一闪' },
    { level: 21, name: '空气刃' },
    { level: 25, name: '神鸟猛击' },
    { level: 29, name: '破坏死光' },
    { level: 33, name: '勇鸟猛攻' }
  ],
  '绿毛虫': [
    { level: 1, name: '撞击' },
    { level: 5, name: '吐丝' },
    { level: 7, name: '虫咬' }
  ],
  '铁甲蛹': [
    { level: 1, name: '变硬' },
    { level: 7, name: '吐丝' }
  ],
  '巴大蝶': [
    { level: 1, name: '冲击' },
    { level: 10, name: '蝶舞' },
    { level: 13, name: '精神强念' },
    { level: 17, name: '暴风' },
    { level: 21, name: '幻象光线' },
    { level: 25, name: '吸取' },
    { level: 29, name: '虫鸣' }
  ],
  '独角虫': [
    { level: 1, name: '撞击' },
    { level: 5, name: '毒针' },
    { level: 7, name: '吐丝' }
  ],
  '铁壳蛹': [
    { level: 1, name: '变硬' },
    { level: 7, name: '毒针' }
  ],
  '大针蜂': [
    { level: 1, name: '毒针' },
    { level: 1, name: '飞弹针' },
    { level: 1, name: '双针' },
    { level: 1, name: '致命针刺' },
    { level: 10, name: '双针' },
    { level: 15, name: '飞弹针' },
    { level: 20, name: '致命针刺' },
    { level: 25, name: '追击' },
    { level: 30, name: '毒尾' },
    { level: 35, name: '破坏死光' }
  ],
  '走路草': [
    { level: 1, name: '撞击' },
    { level: 7, name: '麻痹粉' },
    { level: 9, name: '毒粉' },
    { level: 11, name: '睡眠粉' },
    { level: 13, name: '吸取' },
    { level: 15, name: '寄生种子' },
    { level: 17, name: '超级吸取' },
    { level: 19, name: '生长' },
    { level: 21, name: '毒液冲击' },
    { level: 23, name: '能量球' },
    { level: 25, name: '污泥炸弹' },
    { level: 27, name: '花瓣舞' }
  ],
  '小拳石': [
    { level: 1, name: '冲击' },
    { level: 5, name: '变硬' },
    { level: 10, name: '滚动' },
    { level: 15, name: '岩崩' },
    { level: 20, name: '地震' },
    { level: 25, name: '尖石攻击' },
    { level: 30, name: '大爆炸' },
    { level: 35, name: '破坏死光' }
  ],
  '小火马': [
    { level: 1, name: '火花' },
    { level: 5, name: '嘶叫' },
    { level: 9, name: '飞踢' },
    { level: 13, name: '火焰轮' },
    { level: 17, name: '电光一闪' },
    { level: 21, name: '烈焰冲锋' },
    { level: 25, name: '神速' },
    { level: 29, name: '大字爆炎' },
    { level: 33, name: '破坏死光' }
  ],
  '凯西': [
    { level: 1, name: '瞬间移动' },
    { level: 5, name: '念力' },
    { level: 10, name: '幻象光线' },
    { level: 15, name: '冥想' },
    { level: 20, name: '精神强念' },
    { level: 25, name: '反射壁' },
    { level: 30, name: '食梦' }
  ],
  '杰尼龟': [
    { level: 1, name: '撞击' },
    { level: 4, name: '摇尾巴' },
    { level: 7, name: '水枪' },
    { level: 10, name: '缩入壳中' },
    { level: 13, name: '泡沫' },
    { level: 16, name: '高速旋转' },
    { level: 19, name: '咬咬' },
    { level: 22, name: '水炮' },
    { level: 25, name: '保护色' },
    { level: 28, name: '冲浪' },
    { level: 31, name: '冰冻光束' },
    { level: 34, name: '铁壁' },
    { level: 37, name: '破坏死光' }
  ],
  '小火龙': [
    { level: 1, name: '撞击' },
    { level: 4, name: '叫声' },
    { level: 7, name: '火花' },
    { level: 10, name: '烟幕' },
    { level: 13, name: '金属爪' },
    { level: 16, name: '火焰牙' },
    { level: 19, name: '火焰旋涡' },
    { level: 22, name: '喷射火焰' },
    { level: 25, name: '钢翼' },
    { level: 28, name: '火焰拳' },
    { level: 31, name: '大字爆炎' },
    { level: 34, name: '破坏死光' }
  ],
  '妙蛙种子': [
    { level: 1, name: '撞击' },
    { level: 4, name: '叫声' },
    { level: 7, name: '藤鞭' },
    { level: 10, name: '生长' },
    { level: 13, name: '寄生种子' },
    { level: 16, name: '毒粉' },
    { level: 19, name: '睡眠粉' },
    { level: 22, name: '超级吸取' },
    { level: 25, name: '光合作用' },
    { level: 28, name: '飞叶快刀' },
    { level: 31, name: '能量球' },
    { level: 34, name: '日光束' },
    { level: 37, name: '叶刃' }
  ],
  '皮卡丘': [
    { level: 1, name: '撞击' },
    { level: 5, name: '电击' },
    { level: 9, name: '叫声' },
    { level: 13, name: '电光一闪' },
    { level: 17, name: '电磁波' },
    { level: 21, name: '十万伏特' },
    { level: 25, name: '打雷' },
    { level: 29, name: '神速' },
    { level: 33, name: '破坏死光' }
  ]
}

module.exports = LEARNABLE_MOVES
