const MOVE_DATABASE = {
  '撞击': { name: '撞击', power: 40, accuracy: 100, pp: 35, type: '一般', category: 'physical', effect: null, description: '用整个身体撞向对手' },
  '拍打': { name: '拍打', power: 40, accuracy: 100, pp: 35, type: '一般', category: 'physical', effect: null, description: '使用长长的尾巴或手脚拍打' },
  '抓': { name: '抓', power: 40, accuracy: 100, pp: 35, type: '一般', category: 'physical', effect: null, description: '用爪子抓对手' },
  '电光一闪': { name: '电光一闪', power: 40, accuracy: 100, pp: 30, type: '一般', category: 'physical', effect: { priority: 1 }, description: '以迅雷不及掩耳之势撞击' },
  '叫声': { name: '叫声', power: 0, accuracy: 100, pp: 40, type: '一般', category: 'status', effect: { statDrop: '攻击', amount: 1 }, description: '发出叫声，降低对手的攻击' },
  '摇尾巴': { name: '摇尾巴', power: 0, accuracy: 100, pp: 30, type: '一般', category: 'status', effect: { statDrop: '防御', amount: 1 }, description: '摇尾巴卖萌，降低对手的防御' },
  '瞪眼': { name: '瞪眼', power: 0, accuracy: 100, pp: 30, type: '一般', category: 'status', effect: { statDrop: '防御', amount: 1 }, description: '锐利的眼神使对手害怕' },
  '聚气': { name: '聚气', power: 0, accuracy: 100, pp: 30, type: '一般', category: 'status', effect: { statBoost: '命中', amount: 1 }, description: '集中精神，提高命中率' },
  '变硬': { name: '变硬', power: 0, accuracy: 100, pp: 30, type: '一般', category: 'status', effect: { statBoost: '防御', amount: 1 }, description: '硬化身体，提高防御' },
  '防御卷曲': { name: '防御卷曲', power: 0, accuracy: 100, pp: 40, type: '一般', category: 'status', effect: { statBoost: '防御', amount: 1 }, description: '卷曲身体，提高防御' },
  '剑舞': { name: '剑舞', power: 0, accuracy: 100, pp: 20, type: '一般', category: 'status', effect: { statBoost: '攻击', amount: 2 }, description: '激烈地跳舞，大幅提高攻击' },
  '变圆': { name: '变圆', power: 0, accuracy: 100, pp: 40, type: '一般', category: 'status', effect: { statBoost: '防御', amount: 1 }, description: '身体变圆，提高防御' },
  '高速移动': { name: '高速移动', power: 0, accuracy: 100, pp: 30, type: '超能力', category: 'status', effect: { statBoost: '速度', amount: 2 }, description: '放松身体，提高速度' },
  '唱歌': { name: '唱歌', power: 0, accuracy: 55, pp: 15, type: '一般', category: 'status', effect: { status: 'sleep' }, description: '唱出摇篮曲使对手睡着' },
  '打鼾': { name: '打鼾', power: 50, accuracy: 100, pp: 15, type: '一般', category: 'special', effect: { requiresStatus: 'sleep' }, description: '睡觉时发出鼾声攻击' },
  '睡觉': { name: '睡觉', power: 0, accuracy: 100, pp: 10, type: '超能力', category: 'status', effect: { heal: 1.0, status: 'sleep', turns: 2 }, description: '睡2回合，完全恢复HP' },
  '打盹': { name: '打盹', power: 0, accuracy: 100, pp: 10, type: '超能力', category: 'status', effect: { heal: 0.5, status: 'sleep' }, description: '打盹恢复HP' },
  '治愈之愿': { name: '治愈之愿', power: 0, accuracy: 100, pp: 10, type: '一般', category: 'status', effect: { heal: 1.0, faintUser: true }, description: '牺牲自己使同伴完全恢复' },
  '光合作用': { name: '光合作用', power: 0, accuracy: 100, pp: 5, type: '草', category: 'status', effect: { heal: 0.5 }, description: '吸收阳光恢复HP' },
  '晨光': { name: '晨光', power: 0, accuracy: 100, pp: 5, type: '一般', category: 'status', effect: { heal: 0.5 }, description: '恢复HP' },
  '破坏死光': { name: '破坏死光', power: 150, accuracy: 90, pp: 5, type: '一般', category: 'special', effect: { rechargeTurn: true }, description: '向对手发射强力光线，自己会停顿' },
  '百万吨重拳': { name: '百万吨重拳', power: 80, accuracy: 85, pp: 20, type: '一般', category: 'physical', effect: null, description: '用强力拳头攻击' },
  '百万吨重踢': { name: '百万吨重踢', power: 120, accuracy: 75, pp: 5, type: '一般', category: 'physical', effect: null, description: '用强力踢击' },
  '泰山压顶': { name: '泰山压顶', power: 85, accuracy: 100, pp: 15, type: '一般', category: 'physical', effect: null, description: '用身体压住对手' },
  '舍身冲撞': { name: '舍身冲撞', power: 120, accuracy: 100, pp: 15, type: '一般', category: 'physical', effect: { recoil: 0.33 }, description: '舍身撞击，自己也会受伤' },
  '高速星星': { name: '高速星星', power: 60, accuracy: 100, pp: 20, type: '一般', category: 'special', effect: { alwaysHits: true }, description: '发射星星，必定命中' },
  '三角攻击': { name: '三角攻击', power: 80, accuracy: 100, pp: 10, type: '一般', category: 'special', effect: null, description: '用三角形攻击' },
  '撕裂爪': { name: '撕裂爪', power: 75, accuracy: 95, pp: 10, type: '一般', category: 'physical', effect: { criticalRate: 1 }, description: '用利爪撕裂' },
  '疯狂乱抓': { name: '疯狂乱抓', power: 18, accuracy: 80, pp: 15, type: '一般', category: 'physical', effect: { hits: 'random', maxHits: 5 }, description: '用爪子乱抓2-5次' },
  '连斩': { name: '连斩', power: 40, accuracy: 95, pp: 20, type: '一般', category: 'physical', effect: { hitsConsecutive: true }, description: '用镰刀或爪子连续斩击' },
  '居合斩': { name: '居合斩', power: 50, accuracy: 95, pp: 30, type: '一般', category: 'physical', effect: { criticalRate: 1 }, description: '用刀或爪子斩击' },
  '劈开': { name: '劈开', power: 70, accuracy: 100, pp: 20, type: '一般', category: 'physical', effect: null, description: '用斧头或爪子劈开' },
  '头槌': { name: '头槌', power: 70, accuracy: 100, pp: 15, type: '一般', category: 'physical', effect: { chance: 0.3, flinch: true }, description: '用头撞，可能使对手畏缩' },
  '角撞': { name: '角撞', power: 65, accuracy: 100, pp: 25, type: '一般', category: 'physical', effect: { chance: 0.3, flinch: true }, description: '用尖锐的角撞' },
  '猛撞': { name: '猛撞', power: 90, accuracy: 85, pp: 20, type: '一般', category: 'physical', effect: { chance: 0.3, flinch: true }, description: '用全身猛撞' },
  '冲击': { name: '冲击', power: 50, accuracy: 100, pp: 35, type: '一般', category: 'physical', effect: null, description: '用身体撞击' },
  '撞击': { name: '撞击', power: 40, accuracy: 100, pp: 35, type: '一般', category: 'physical', effect: null, description: '用身体撞' },
  '坚硬': { name: '坚硬', power: 0, accuracy: 100, pp: 30, type: '一般', category: 'status', effect: { statBoost: '防御', amount: 1 }, description: '身体变硬' },
  '甜气': { name: '甜气', power: 0, accuracy: 100, pp: 20, type: '一般', category: 'status', effect: { statDrop: '闪避', amount: 2 }, description: '散发甜气' },
  '舔': { name: '舔', power: 30, accuracy: 100, pp: 30, type: '幽灵', category: 'physical', effect: { chance: 0.3, status: 'paralysis' }, description: '用长舌头舔' },
  '咬': { name: '咬', power: 60, accuracy: 100, pp: 25, type: '恶', category: 'physical', effect: { chance: 0.3, flinch: true }, description: '用尖锐的牙咬' },
  '咬碎': { name: '咬碎', power: 80, accuracy: 100, pp: 15, type: '恶', category: 'physical', effect: { chance: 0.2, statDrop: '防御', amount: 1 }, description: '用力咬碎' },
  '吼': { name: '吼', power: 0, accuracy: 100, pp: 20, type: '一般', category: 'status', effect: { statDrop: '攻击', amount: 1 }, description: '吼叫威吓' },
  '聚宝功': { name: '聚宝功', power: 40, accuracy: 100, pp: 20, type: '一般', category: 'physical', effect: null, description: '投掷金币攻击' },
  '火焰牙': { name: '火焰牙', power: 65, accuracy: 95, pp: 15, type: '火', category: 'physical', effect: { chance: 0.1, status: 'burn' }, description: '用灼热的牙咬' },
  '冰冻牙': { name: '冰冻牙', power: 65, accuracy: 95, pp: 15, type: '冰', category: 'physical', effect: { chance: 0.1, status: 'freeze' }, description: '用冰冷的牙咬' },
  '雷电牙': { name: '雷电牙', power: 65, accuracy: 95, pp: 15, type: '电', category: 'physical', effect: { chance: 0.1, status: 'paralysis' }, description: '用带电的牙咬' },
  '毒针': { name: '毒针', power: 15, accuracy: 100, pp: 35, type: '毒', category: 'physical', effect: { chance: 0.3, status: 'poison' }, description: '用毒针刺' },
  '毒牙': { name: '毒牙', power: 50, accuracy: 100, pp: 25, type: '毒', category: 'physical', effect: { chance: 0.2, status: 'poison' }, description: '用毒牙咬' },
  '毒尾': { name: '毒尾', power: 50, accuracy: 100, pp: 25, type: '毒', category: 'physical', effect: { chance: 0.1, status: 'poison' }, description: '用毒尾击' },
  '剧毒': { name: '剧毒', power: 0, accuracy: 90, pp: 10, type: '毒', category: 'status', effect: { status: 'badPoison' }, description: '使对手中剧毒' },
  '毒液冲击': { name: '毒液冲击', power: 65, accuracy: 100, pp: 10, type: '毒', category: 'special', effect: null, description: '投掷毒液' },
  '污泥炸弹': { name: '污泥炸弹', power: 90, accuracy: 100, pp: 10, type: '毒', category: 'special', effect: { chance: 0.3, statDrop: '特防', amount: 1 }, description: '投掷污泥' },
  '溶解液': { name: '溶解液', power: 40, accuracy: 100, pp: 30, type: '毒', category: 'special', effect: { chance: 0.3, statDrop: '特防', amount: 1 }, description: '喷洒溶解液' },
  '酸液炸弹': { name: '酸液炸弹', power: 40, accuracy: 100, pp: 20, type: '毒', category: 'special', effect: { chance: 0.1, statDrop: '特防', amount: 2 }, description: '投掷强酸' },
  '火花': { name: '火花', power: 40, accuracy: 100, pp: 25, type: '火', category: 'special', effect: { chance: 0.1, status: 'burn' }, description: '喷出小火' },
  '火焰弹': { name: '火焰弹', power: 65, accuracy: 100, pp: 15, type: '火', category: 'special', effect: { chance: 0.1, status: 'burn' }, description: '投掷火焰弹' },
  '喷射火焰': { name: '喷射火焰', power: 90, accuracy: 100, pp: 15, type: '火', category: 'special', effect: { chance: 0.1, status: 'burn' }, description: '喷出强烈火焰' },
  '大字爆炎': { name: '大字爆炎', power: 110, accuracy: 85, pp: 5, type: '火', category: 'special', effect: { chance: 0.1, status: 'burn' }, description: '释放大字型烈焰' },
  '火焰拳': { name: '火焰拳', power: 75, accuracy: 100, pp: 15, type: '火', category: 'physical', effect: { chance: 0.1, status: 'burn' }, description: '用火焰包裹的拳头' },
  '火焰轮': { name: '火焰轮', power: 60, accuracy: 100, pp: 25, type: '火', category: 'physical', effect: { chance: 0.1, status: 'burn' }, description: '用火焰包裹身体滚动' },
  '烈焰冲锋': { name: '烈焰冲锋', power: 120, accuracy: 100, pp: 15, type: '火', category: 'physical', effect: { chance: 0.1, status: 'burn', recoil: 0.33 }, description: '带火焰的舍身撞击' },
  '烟幕': { name: '烟幕', power: 0, accuracy: 100, pp: 20, type: '火', category: 'status', effect: { statDrop: '命中', amount: 1 }, description: '释放烟幕' },
  '烈暴风': { name: '烈暴风', power: 40, accuracy: 100, pp: 25, type: '飞行', category: 'special', effect: null, description: '卷起烈风' },
  '翅膀攻击': { name: '翅膀攻击', power: 60, accuracy: 100, pp: 35, type: '飞行', category: 'physical', effect: null, description: '用翅膀拍打' },
  '空气切割': { name: '空气切割', power: 75, accuracy: 95, pp: 15, type: '飞行', category: 'special', effect: { chance: 0.3, flinch: true }, description: '用锋利的气流切割' },
  '空气刃': { name: '空气刃', power: 60, accuracy: 95, pp: 25, type: '飞行', category: 'special', effect: { criticalRate: 1 }, description: '用风刃攻击' },
  '神鸟猛击': { name: '神鸟猛击', power: 140, accuracy: 90, pp: 5, type: '飞行', category: 'physical', effect: { recoil: 0.5 }, description: '舍身撞击，有较大反伤' },
  '勇鸟猛攻': { name: '勇鸟猛攻', power: 120, accuracy: 100, pp: 15, type: '飞行', category: 'physical', effect: { recoil: 0.33 }, description: '用全身撞击，会受伤' },
  '飞翔': { name: '飞翔', power: 90, accuracy: 95, pp: 15, type: '飞行', category: 'physical', effect: { chargeTurn: true }, description: '第1回合飞起，第2回合攻击' },
  '啄': { name: '啄', power: 35, accuracy: 100, pp: 35, type: '飞行', category: 'physical', effect: null, description: '用尖嘴啄' },
  '龙卷风': { name: '龙卷风', power: 40, accuracy: 100, pp: 20, type: '龙', category: 'special', effect: { chance: 0.2, flinch: true }, description: '卷起龙卷风' },
  '龙息': { name: '龙息', power: 60, accuracy: 100, pp: 20, type: '龙', category: 'special', effect: { chance: 0.3, status: 'paralysis' }, description: '喷出龙息' },
  '龙爪': { name: '龙爪', power: 80, accuracy: 100, pp: 15, type: '龙', category: 'physical', effect: null, description: '用利爪撕裂' },
  '龙之怒': { name: '龙之怒', power: 0, accuracy: 100, pp: 10, type: '龙', category: 'special', effect: { fixedDamage: 40 }, description: '必定造成40点伤害' },
  '水枪': { name: '水枪', power: 40, accuracy: 100, pp: 25, type: '水', category: 'special', effect: null, description: '喷出水枪' },
  '泡沫光线': { name: '泡沫光线', power: 65, accuracy: 100, pp: 20, type: '水', category: 'special', effect: { chance: 0.3, statDrop: '速度', amount: 1 }, description: '喷出泡沫' },
  '冲浪': { name: '冲浪', power: 90, accuracy: 100, pp: 15, type: '水', category: 'special', effect: null, description: '乘大浪冲击' },
  '水炮': { name: '水炮', power: 110, accuracy: 80, pp: 5, type: '水', category: 'special', effect: null, description: '喷出强力水柱' },
  '潜水': { name: '潜水', power: 80, accuracy: 100, pp: 10, type: '水', category: 'physical', effect: { chargeTurn: true }, description: '潜入水中攻击' },
  '冰冻光束': { name: '冰冻光束', power: 90, accuracy: 100, pp: 10, type: '冰', category: 'special', effect: { chance: 0.1, status: 'freeze' }, description: '发射冰冻光束' },
  '冰冻之风': { name: '冰冻之风', power: 55, accuracy: 95, pp: 15, type: '冰', category: 'special', effect: { chance: 1.0, statDrop: '速度', amount: 1 }, description: '吹出冰冷的风' },
  '暴风雪': { name: '暴风雪', power: 110, accuracy: 70, pp: 5, type: '冰', category: 'special', effect: { chance: 0.1, status: 'freeze' }, description: '召唤暴风雪' },
  '急冻光线': { name: '急冻光线', power: 90, accuracy: 100, pp: 10, type: '冰', category: 'special', effect: { chance: 0.1, status: 'freeze' }, description: '发射急冻光线' },
  '急冻拳': { name: '急冻拳', power: 75, accuracy: 100, pp: 15, type: '冰', category: 'physical', effect: { chance: 0.1, status: 'freeze' }, description: '用冰冻的拳头' },
  '电击': { name: '电击', power: 40, accuracy: 100, pp: 30, type: '电', category: 'special', effect: { chance: 0.1, status: 'paralysis' }, description: '发出电击' },
  '十万伏特': { name: '十万伏特', power: 90, accuracy: 100, pp: 15, type: '电', category: 'special', effect: { chance: 0.1, status: 'paralysis' }, description: '释放十万伏特电力' },
  '打雷': { name: '打雷', power: 110, accuracy: 70, pp: 10, type: '电', category: 'special', effect: { chance: 0.3, status: 'paralysis' }, description: '召唤雷电' },
  '雷电': { name: '雷电', power: 110, accuracy: 70, pp: 10, type: '电', category: 'special', effect: { chance: 0.3, status: 'paralysis' }, description: '落下雷电' },
  '雷电拳': { name: '雷电拳', power: 75, accuracy: 100, pp: 15, type: '电', category: 'physical', effect: { chance: 0.1, status: 'paralysis' }, description: '用带电的拳头' },
  '电磁波': { name: '电磁波', power: 0, accuracy: 90, pp: 20, type: '电', category: 'status', effect: { status: 'paralysis' }, description: '放出电磁波使对手麻痹' },
  '充电': { name: '充电', power: 0, accuracy: 100, pp: 20, type: '电', category: 'status', effect: { statBoost: '特防', amount: 1 }, description: '充电提高特防' },
  '放电': { name: '放电', power: 80, accuracy: 100, pp: 15, type: '电', category: 'special', effect: { chance: 0.3, status: 'paralysis' }, description: '释放电力' },
  '藤鞭': { name: '藤鞭', power: 45, accuracy: 100, pp: 25, type: '草', category: 'physical', effect: null, description: '用藤鞭抽打' },
  '吸取': { name: '吸取', power: 20, accuracy: 100, pp: 25, type: '草', category: 'special', effect: { drain: 0.5 }, description: '吸取对手HP' },
  '超级吸取': { name: '超级吸取', power: 40, accuracy: 100, pp: 15, type: '草', category: 'special', effect: { drain: 0.5 }, description: '大量吸取' },
  '飞叶快刀': { name: '飞叶快刀', power: 55, accuracy: 95, pp: 25, type: '草', category: 'physical', effect: { criticalRate: 1 }, description: '投掷锋利的叶片' },
  '叶刃': { name: '叶刃', power: 90, accuracy: 100, pp: 10, type: '草', category: 'physical', effect: { criticalRate: 1 }, description: '用叶刃切割' },
  '日光束': { name: '日光束', power: 120, accuracy: 100, pp: 10, type: '草', category: 'special', effect: { chargeTurn: true }, description: '第1回合蓄力，第2回合发射' },
  '能量球': { name: '能量球', power: 80, accuracy: 100, pp: 10, type: '草', category: 'special', effect: { chance: 0.1, statDrop: '特防', amount: 1 }, description: '发射能量球' },
  '种子机关枪': { name: '种子机关枪', power: 25, accuracy: 100, pp: 30, type: '草', category: 'physical', effect: { hits: 'random', maxHits: 5 }, description: '发射多枚种子' },
  '强力鞭打': { name: '强力鞭打', power: 120, accuracy: 85, pp: 10, type: '草', category: 'physical', effect: null, description: '用强力藤鞭' },
  '花瓣舞': { name: '花瓣舞', power: 120, accuracy: 100, pp: 10, type: '草', category: 'special', effect: { multiTurn: 3, confusionAfter: true }, description: '连续2回合花瓣舞，结束后混乱' },
  '寄生种子': { name: '寄生种子', power: 0, accuracy: 90, pp: 10, type: '草', category: 'status', effect: { leechSeed: true }, description: '种植寄生种子' },
  '麻痹粉': { name: '麻痹粉', power: 0, accuracy: 75, pp: 35, type: '草', category: 'status', effect: { status: 'paralysis' }, description: '撒麻痹粉' },
  '毒粉': { name: '毒粉', power: 0, accuracy: 75, pp: 35, type: '毒', category: 'status', effect: { status: 'poison' }, description: '撒毒粉' },
  '睡眠粉': { name: '睡眠粉', power: 0, accuracy: 75, pp: 15, type: '草', category: 'status', effect: { status: 'sleep' }, description: '撒睡眠粉' },
  '蘑菇孢子': { name: '蘑菇孢子', power: 0, accuracy: 100, pp: 15, type: '草', category: 'status', effect: { status: 'sleep' }, description: '释放蘑菇孢子' },
  '生长': { name: '生长', power: 0, accuracy: 100, pp: 20, type: '一般', category: 'status', effect: { statBoost: '特攻', amount: 1 }, description: '身体成长' },
  '吐丝': { name: '吐丝', power: 0, accuracy: 95, pp: 40, type: '虫', category: 'status', effect: { statDrop: '速度', amount: 1 }, description: '吐丝缠住' },
  '虫咬': { name: '虫咬', power: 60, accuracy: 100, pp: 20, type: '虫', category: 'physical', effect: null, description: '咬住' },
  '吸血': { name: '吸血', power: 80, accuracy: 100, pp: 10, type: '虫', category: 'physical', effect: { drain: 0.5 }, description: '吸血' },
  '飞弹针': { name: '飞弹针', power: 25, accuracy: 95, pp: 20, type: '虫', category: 'physical', effect: { hits: 'random', maxHits: 5 }, description: '发射多枚飞弹针' },
  '双针': { name: '双针', power: 25, accuracy: 100, pp: 20, type: '虫', category: 'physical', effect: { hits: 2 }, description: '用2根针刺2次' },
  '致命针刺': { name: '致命针刺', power: 50, accuracy: 100, pp: 25, type: '虫', category: 'physical', effect: null, description: '用致命的针刺' },
  '夹住': { name: '夹住', power: 55, accuracy: 100, pp: 30, type: '一般', category: 'physical', effect: null, description: '用钳子夹住' },
  '剪十字': { name: '剪十字', power: 80, accuracy: 100, pp: 10, type: '虫', category: 'physical', effect: null, description: '用剪刀交叉攻击' },
  '刀背打': { name: '刀背打', power: 40, accuracy: 100, pp: 25, type: '虫', category: 'physical', effect: null, description: '用刀背打击' },
  '蝶舞': { name: '蝶舞', power: 0, accuracy: 100, pp: 20, type: '虫', category: 'status', effect: { statBoost: '特攻', amount: 1, statBoost2: '特防', amount: 1, statBoost3: '速度', amount: 1 }, description: '跳舞，特攻、特防、速度提升' },
  '滚动': { name: '滚动', power: 30, accuracy: 90, pp: 20, type: '岩石', category: 'physical', effect: { powerDoublesEachTurn: true }, description: '滚动攻击，威力逐回合翻倍' },
  '岩石打磨': { name: '岩石打磨', power: 0, accuracy: 100, pp: 20, type: '岩石', category: 'status', effect: { statBoost: '速度', amount: 2 }, description: '打磨岩石，提高速度' },
  '尖石攻击': { name: '尖石攻击', power: 100, accuracy: 80, pp: 5, type: '岩石', category: 'physical', effect: null, description: '用尖石攻击' },
  '岩崩': { name: '岩崩', power: 75, accuracy: 90, pp: 10, type: '岩石', category: 'physical', effect: { chance: 0.3, flinch: true }, description: '投掷岩石' },
  '岩石封锁': { name: '岩石封锁', power: 60, accuracy: 95, pp: 15, type: '岩石', category: 'physical', effect: { chance: 1.0, statDrop: '速度', amount: 1 }, description: '用岩石封锁' },
  '沙尘暴': { name: '沙尘暴', power: 0, accuracy: 100, pp: 10, type: '岩石', category: 'status', effect: { weather: 'sandstorm' }, description: '制造沙尘暴' },
  '地震': { name: '地震', power: 100, accuracy: 100, pp: 10, type: '地面', category: 'physical', effect: null, description: '用地震攻击' },
  '泼沙': { name: '泼沙', power: 0, accuracy: 100, pp: 15, type: '地面', category: 'status', effect: { statDrop: '命中', amount: 1 }, description: '向对手脸上泼沙' },
  '挖洞': { name: '挖洞', power: 80, accuracy: 100, pp: 10, type: '地面', category: 'physical', effect: { chargeTurn: true }, description: '挖洞攻击' },
  '撒菱': { name: '撒菱', power: 0, accuracy: 100, pp: 20, type: '地面', category: 'status', effect: null, description: '在地面撒菱' },
  '精神强念': { name: '精神强念', power: 90, accuracy: 100, pp: 10, type: '超能力', category: 'special', effect: { chance: 0.1, statDrop: '特防', amount: 1 }, description: '释放强力念力' },
  '念力': { name: '念力', power: 50, accuracy: 100, pp: 25, type: '超能力', category: 'special', effect: { chance: 0.3, flinch: true }, description: '使用念力' },
  '幻象光线': { name: '幻象光线', power: 65, accuracy: 100, pp: 20, type: '超能力', category: 'special', effect: { chance: 0.1, confusion: true }, description: '发射幻象光线' },
  '食梦': { name: '食梦', power: 100, accuracy: 100, pp: 15, type: '超能力', category: 'special', effect: { heal: 0.5, requiresStatus: 'sleep' }, description: '在对手睡眠时吸取HP' },
  '瞬间移动': { name: '瞬间移动', power: 0, accuracy: 100, pp: 20, type: '超能力', category: 'status', effect: { teleport: true }, description: '瞬间移动逃跑' },
  '冥想': { name: '冥想', power: 0, accuracy: 100, pp: 20, type: '超能力', category: 'status', effect: { statBoost: '特攻', amount: 1, statBoost2: '特防', amount: 1 }, description: '冥想，特攻、特防提升' },
  '反射壁': { name: '反射壁', power: 0, accuracy: 100, pp: 20, type: '超能力', category: 'status', effect: { teamDefense: true }, description: '制造反射壁' },
  '光墙': { name: '光墙', power: 0, accuracy: 100, pp: 20, type: '超能力', category: 'status', effect: { teamSpecialDefense: true }, description: '制造光墙' },
  '影子球': { name: '影子球', power: 80, accuracy: 100, pp: 15, type: '幽灵', category: 'special', effect: { chance: 0.2, statDrop: '特防', amount: 1 }, description: '投掷影子球' },
  '暗影爪': { name: '暗影爪', power: 70, accuracy: 100, pp: 15, type: '幽灵', category: 'physical', effect: { criticalRate: 1 }, description: '用影子爪子' },
  '诅咒': { name: '诅咒', power: 0, accuracy: 100, pp: 10, type: '幽灵', category: 'status', effect: { statBoost: '攻击', amount: 1, statDrop: '速度', amount: 1 }, description: '诅咒，攻击提升速度下降' },
  '惊吓': { name: '惊吓', power: 30, accuracy: 100, pp: 15, type: '幽灵', category: 'physical', effect: { chance: 0.3, flinch: true }, description: '惊吓对手' },
  '石化功': { name: '石化功', power: 40, accuracy: 100, pp: 20, type: '一般', category: 'physical', effect: null, description: '使对手石化' },
  '追击': { name: '追击', power: 40, accuracy: 100, pp: 20, type: '恶', category: 'physical', effect: null, description: '追击' },
  '暗袭要害': { name: '暗袭要害', power: 70, accuracy: 100, pp: 15, type: '恶', category: 'physical', effect: { criticalRate: 1, ignoresProtect: true }, description: '偷袭要害，必定击中要害' },
  '突袭': { name: '突袭', power: 80, accuracy: 100, pp: 5, type: '恶', category: 'physical', effect: { priority: 1, onlyIfFaster: true }, description: '先制攻击' },
  '击掌奇袭': { name: '击掌奇袭', power: 40, accuracy: 100, pp: 10, type: '恶', category: 'physical', effect: { priority: 1, chance: 1.0, flinch: true }, description: '先制拍击' },
  '欺诈': { name: '欺诈', power: 95, accuracy: 100, pp: 15, type: '恶', category: 'special', effect: { usesTargetAttack: true }, description: '利用对手的物攻' },
  '空手劈': { name: '空手劈', power: 50, accuracy: 100, pp: 25, type: '格斗', category: 'physical', effect: null, description: '用手刀劈' },
  '手刀': { name: '手刀', power: 40, accuracy: 100, pp: 25, type: '格斗', category: 'physical', effect: null, description: '用双手劈' },
  '劈瓦': { name: '劈瓦', power: 75, accuracy: 100, pp: 15, type: '格斗', category: 'physical', effect: null, description: '用强大的力量劈开岩石' },
  '地球上投': { name: '地球上投', power: 0, accuracy: 100, pp: 20, type: '格斗', category: 'physical', effect: { damageByLevel: true }, description: '将对手摔到地上' },
  '十字切': { name: '十字切', power: 100, accuracy: 80, pp: 5, type: '格斗', category: 'physical', effect: { criticalRate: 1 }, description: '用双手交叉劈' },
  '臂锤': { name: '臂锤', power: 100, accuracy: 90, pp: 10, type: '格斗', category: 'physical', effect: { statDrop: '速度', amount: 1 }, description: '用强力手臂锤击' },
  '劲力': { name: '劲力', power: 80, accuracy: 100, pp: 15, type: '格斗', category: 'physical', effect: { chance: 0.3, statDrop: '防御', amount: 1 }, description: '用强力打击' },
  '爆裂拳': { name: '爆裂拳', power: 100, accuracy: 50, pp: 5, type: '格斗', category: 'physical', effect: { confusion: true }, description: '可能使对手混乱' },
  '集中猛击': { name: '集中猛击', power: 100, accuracy: 100, pp: 5, type: '格斗', category: 'physical', effect: { requiresFocus: true }, description: '在聚气后强力打击' },
  '踢倒': { name: '踢倒', power: 60, accuracy: 100, pp: 20, type: '格斗', category: 'physical', effect: null, description: '踢倒对手' },
  '飞踢': { name: '飞踢', power: 100, accuracy: 95, pp: 10, type: '格斗', category: 'physical', effect: { missRecoil: true }, description: '跳跃踢击' },
  '飞膝踢': { name: '飞膝踢', power: 130, accuracy: 90, pp: 10, type: '格斗', category: 'physical', effect: { missRecoil: true }, description: '用膝盖强力撞击' },
  '弹跳': { name: '弹跳', power: 85, accuracy: 85, pp: 5, type: '飞行', category: 'physical', effect: { chargeTurn: true }, description: '弹跳攻击' },
  '神速': { name: '神速', power: 80, accuracy: 100, pp: 5, type: '一般', category: 'physical', effect: { priority: 2 }, description: '极速先制攻击' },
  '钢翼': { name: '钢翼', power: 70, accuracy: 90, pp: 25, type: '钢', category: 'physical', effect: { chance: 0.3, statBoost: '防御', amount: 1 }, description: '用钢翼攻击' },
  '金属爪': { name: '金属爪', power: 50, accuracy: 95, pp: 35, type: '钢', category: 'physical', effect: { chance: 0.1, statBoost: '攻击', amount: 1 }, description: '用金属爪子' },
  '铁头': { name: '铁头', power: 80, accuracy: 100, pp: 15, type: '钢', category: 'physical', effect: { chance: 0.3, flinch: true }, description: '用铁头撞击' },
  '铁壁': { name: '铁壁', power: 0, accuracy: 100, pp: 15, type: '钢', category: 'status', effect: { statBoost: '防御', amount: 2 }, description: '铁化皮肤，大幅提高防御' },
  '铁尾': { name: '铁尾', power: 100, accuracy: 75, pp: 15, type: '钢', category: 'physical', effect: { chance: 0.3, statDrop: '防御', amount: 1 }, description: '用铁尾攻击' },
  '金属音': { name: '金属音', power: 0, accuracy: 85, pp: 40, type: '钢', category: 'status', effect: { statDrop: '特防', amount: 2 }, description: '发出刺耳的金属音' },
  '妖精之风': { name: '妖精之风', power: 40, accuracy: 100, pp: 30, type: '妖精', category: 'special', effect: null, description: '吹出妖精风' },
  '魔法闪耀': { name: '魔法闪耀', power: 80, accuracy: 100, pp: 10, type: '妖精', category: 'special', effect: null, description: '释放魔法光' },
  '魅惑之声': { name: '魅惑之声', power: 40, accuracy: 100, pp: 15, type: '妖精', category: 'special', effect: { alwaysHits: true }, description: '释放魅惑的声音' },
  '撒娇': { name: '撒娇', power: 0, accuracy: 100, pp: 20, type: '妖精', category: 'status', effect: { statDrop: '攻击', amount: 2 }, description: '撒娇使对手松懈' },
  '迷人': { name: '迷人', power: 0, accuracy: 100, pp: 15, type: '一般', category: 'status', effect: { attract: true }, description: '迷人使对手着迷' },
  '轮唱': { name: '轮唱', power: 60, accuracy: 100, pp: 10, type: '一般', category: 'special', effect: { hits: 'continuous' }, description: '连续攻击' },
  '高音': { name: '高音', power: 90, accuracy: 100, pp: 10, type: '一般', category: 'special', effect: null, description: '发出高音' },
  '虫鸣': { name: '虫鸣', power: 90, accuracy: 100, pp: 10, type: '虫', category: 'special', effect: null, description: '发出虫鸣' },
  '超声波': { name: '超声波', power: 0, accuracy: 55, pp: 20, type: '一般', category: 'status', effect: { confusion: true }, description: '发出特殊声波' },
  '刺耳声': { name: '刺耳声', power: 0, accuracy: 85, pp: 40, type: '一般', category: 'status', effect: { statDrop: '防御', amount: 2 }, description: '发出刺耳声' },
  '吼叫': { name: '吼叫', power: 0, accuracy: 100, pp: 20, type: '一般', category: 'status', effect: null, description: '吓退野生宝可梦' },
  '吹飞': { name: '吹飞', power: 0, accuracy: 100, pp: 20, type: '一般', category: 'status', effect: null, description: '吹飞' },
  '黑色目光': { name: '黑色目光', power: 0, accuracy: 100, pp: 5, type: '一般', category: 'status', effect: { preventEscape: true }, description: '阻止对手逃跑' },
  '愤怒': { name: '愤怒', power: 20, accuracy: 100, pp: 20, type: '一般', category: 'physical', effect: { boostsWithDamage: true }, description: '愤怒的打击，攻击随受到伤害提升' },
  '压制': { name: '压制', power: 50, accuracy: 100, pp: 10, type: '一般', category: 'physical', effect: null, description: '压制对手' },
  '大爆炸': { name: '大爆炸', power: 250, accuracy: 100, pp: 5, type: '一般', category: 'physical', effect: { faintUser: true }, description: '自己也会濒死' },
  '自爆': { name: '自爆', power: 250, accuracy: 100, pp: 5, type: '一般', category: 'physical', effect: { faintUser: true }, description: '自爆，自己濒死' },
  '电磁炮': { name: '电磁炮', power: 120, accuracy: 50, pp: 5, type: '电/钢', category: 'special', effect: null, description: '电磁炮攻击' },
  '三角攻击': { name: '三角攻击', power: 80, accuracy: 100, pp: 10, type: '一般', category: 'special', effect: null, description: '三角攻击' },
  '骨头回旋镖': { name: '骨头回旋镖', power: 50, accuracy: 90, pp: 10, type: '地面', category: 'physical', effect: null, description: '投掷骨头' },
  '骨头棒': { name: '骨头棒', power: 65, accuracy: 85, pp: 20, type: '地面', category: 'physical', effect: null, description: '用骨头敲打' },
  '头槌': { name: '头槌', power: 70, accuracy: 100, pp: 15, type: '岩石', category: 'physical', effect: { chance: 0.3, flinch: true }, description: '用头撞' },
  '咬咬': { name: '咬咬', power: 60, accuracy: 100, pp: 25, type: '恶', category: 'physical', effect: { chance: 0.3, flinch: true }, description: '用力咬' },
  '十字毒牙': { name: '十字毒牙', power: 50, accuracy: 100, pp: 15, type: '毒', category: 'physical', effect: { chance: 0.2, status: 'poison' }, description: '用毒牙咬' },
  '硬撑': { name: '硬撑', power: 70, accuracy: 100, pp: 20, type: '一般', category: 'physical', effect: null, description: '在异常状态时威力翻倍' },
  '毒烟': { name: '毒烟', power: 0, accuracy: 100, pp: 20, type: '毒', category: 'status', effect: { chance: 0.4, status: 'poison' }, description: '释放毒烟' },
  '爆炸': { name: '爆炸', power: 250, accuracy: 100, pp: 5, type: '一般', category: 'physical', effect: { faintUser: true }, description: '爆炸攻击' },
  '爆炸烈焰': { name: '爆炸烈焰', power: 150, accuracy: 90, pp: 5, type: '火', category: 'special', effect: { chance: 0.1, status: 'burn' }, description: '爆炸烈焰' },
  '硬化': { name: '硬化', power: 0, accuracy: 100, pp: 30, type: '一般', category: 'status', effect: { statBoost: '防御', amount: 1 }, description: '硬化皮肤' },
  '健美': { name: '健美', power: 0, accuracy: 100, pp: 20, type: '格斗', category: 'status', effect: { statBoost: '攻击', amount: 1, statBoost2: '防御', amount: 1 }, description: '健美，攻防提升' },
  '聚气': { name: '聚气', power: 0, accuracy: 100, pp: 30, type: '一般', category: 'status', effect: { criticalRate: 2 }, description: '聚气，下次攻击必暴击' },
  '挑拨': { name: '挑拨', power: 0, accuracy: 100, pp: 20, type: '恶', category: 'status', effect: { taunt: true }, description: '挑拨对手使其只能用攻击招式' },
  '烟幕': { name: '烟幕', power: 0, accuracy: 100, pp: 20, type: '火', category: 'status', effect: { statDrop: '命中', amount: 1 }, description: '释放烟幕降低命中' },
  '气味侦测': { name: '气味侦测', power: 0, accuracy: 100, pp: 40, type: '一般', category: 'status', effect: null, description: '侦测气味' },
  '电气场地': { name: '电气场地', power: 0, accuracy: 100, pp: 10, type: '电', category: 'status', effect: { terrain: 'electric' }, description: '铺设电气场地' },
  '守住': { name: '守住', power: 0, accuracy: 100, pp: 10, type: '一般', category: 'status', effect: { protect: true }, description: '守住，保护自己' },
  '替身': { name: '替身', power: 0, accuracy: 100, pp: 10, type: '一般', category: 'status', effect: { substitute: true }, description: '制造替身' },
  '忍耐': { name: '忍耐', power: 0, accuracy: 100, pp: 10, type: '一般', category: 'status', effect: { endure: true }, description: '忍耐，必定留下1HP' },
  '自我暗示': { name: '自我暗示', power: 0, accuracy: 100, pp: 10, type: '一般', category: 'status', effect: null, description: '暗示对手' },
  '高速星星': { name: '高速星星', power: 60, accuracy: 100, pp: 20, type: '一般', category: 'special', effect: { alwaysHits: true }, description: '必定命中' },
  '泡沫': { name: '泡沫', power: 40, accuracy: 100, pp: 30, type: '水', category: 'special', effect: { chance: 0.1, statDrop: '速度', amount: 1 }, description: '喷出泡沫' },
  '水溅跃': { name: '水溅跃', power: 0, accuracy: 100, pp: 40, type: '水', category: 'status', effect: null, description: '水溅跃，无伤害' },
  '热水': { name: '热水', power: 80, accuracy: 100, pp: 10, type: '水', category: 'special', effect: { chance: 0.2, status: 'burn' }, description: '喷出热水' },
  '水流喷射': { name: '水流喷射', power: 40, accuracy: 100, pp: 20, type: '水', category: 'special', effect: { priority: 1 }, description: '先制喷水' },
  '帮助': { name: '帮助', power: 0, accuracy: 100, pp: 20, type: '一般', category: 'status', effect: null, description: '帮助同伴' },
  '燃烧殆尽': { name: '燃烧殆尽', power: 130, accuracy: 100, pp: 5, type: '火', category: 'special', effect: null, description: '燃烧殆尽' },
  '超级角击': { name: '超级角击', power: 120, accuracy: 85, pp: 10, type: '一般', category: 'physical', effect: null, description: '用强力角撞击' },
  '龙之舞': { name: '龙之舞', power: 0, accuracy: 100, pp: 20, type: '龙', category: 'status', effect: { statBoost: '攻击', amount: 1, statBoost2: '速度', amount: 1 }, description: '龙之舞，攻速提升' },
  '鳞片噪音': { name: '鳞片噪音', power: 0, accuracy: 100, pp: 40, type: '一般', category: 'status', effect: { statBoost: '防御', amount: 1 }, description: '抖动鳞片' },
  '沙鳞': { name: '沙鳞', power: 0, accuracy: 100, pp: 30, type: '一般', category: 'status', effect: { statBoost: '闪避', amount: 1 }, description: '扬起沙子提升闪避' },
  '尖嘴攻击': { name: '尖嘴攻击', power: 80, accuracy: 100, pp: 10, type: '飞行', category: 'physical', effect: null, description: '用尖锐的嘴攻击' },
  '嘶叫': { name: '嘶叫', power: 0, accuracy: 100, pp: 40, type: '一般', category: 'status', effect: { statDrop: '攻击', amount: 1 }, description: '发出嘶叫降低对手攻击' },
  '击掌奇袭': { name: '击掌奇袭', power: 40, accuracy: 100, pp: 10, type: '一般', category: 'physical', effect: { priority: 1, chance: 0.3, flinch: true }, description: '先制攻击，可能使对手畏缩' },
  '十字毒牙': { name: '十字毒牙', power: 70, accuracy: 100, pp: 15, type: '毒', category: 'physical', effect: { chance: 0.2, status: 'poison', criticalRate: 1 }, description: '十字形毒牙攻击' },
  '自爆': { name: '自爆', power: 200, accuracy: 100, pp: 5, type: '一般', category: 'physical', effect: { faintUser: true }, description: '自爆造成大量伤害' },
  '爆炸': { name: '爆炸', power: 250, accuracy: 100, pp: 5, type: '一般', category: 'physical', effect: { faintUser: true }, description: '引发大爆炸' },
  '大爆炸': { name: '大爆炸', power: 250, accuracy: 100, pp: 5, type: '一般', category: 'physical', effect: { faintUser: true }, description: '巨大爆炸' },
  '岩崩': { name: '岩崩', power: 75, accuracy: 90, pp: 10, type: '岩石', category: 'physical', effect: { chance: 0.3, flinch: true }, description: '岩石崩塌' },
  '神速': { name: '神速', power: 80, accuracy: 100, pp: 5, type: '一般', category: 'physical', effect: { priority: 1 }, description: '极快速度攻击' },
  '反射壁': { name: '反射壁', power: 0, accuracy: 100, pp: 20, type: '超能力', category: 'status', effect: { statBoost: '特防', amount: 2 }, description: '提升特防' },
  '冥想': { name: '冥想', power: 0, accuracy: 100, pp: 20, type: '超能力', category: 'status', effect: { statBoost: '特攻', amount: 1, statBoost2: '特防', amount: 1 }, description: '冥想提升攻防' },
  '食梦': { name: '食梦', power: 100, accuracy: 100, pp: 15, type: '超能力', category: 'special', effect: { heal: 0.5, requiresStatus: 'sleep' }, description: '吞食梦境' },
  '幻象光线': { name: '幻象光线', power: 65, accuracy: 100, pp: 20, type: '超能力', category: 'special', effect: { chance: 0.1, status: 'confusion' }, description: '幻象攻击' },
  '蝶舞': { name: '蝶舞', power: 0, accuracy: 100, pp: 20, type: '虫', category: 'status', effect: { statBoost: '特攻', amount: 1, statBoost2: '特防', amount: 1, statBoost3: '速度', amount: 1 }, description: '蝴蝶之舞提升能力' },
  '暴风': { name: '暴风', power: 110, accuracy: 70, pp: 10, type: '飞行', category: 'special', effect: { chance: 0.3, statDrop: '特防', amount: 1 }, description: '召唤暴风' },
  '寄生种子': { name: '寄生种子', power: 0, accuracy: 90, pp: 10, type: '草', category: 'status', effect: { leechSeed: true }, description: '种植寄生种子' },
  '超级吸取': { name: '超级吸取', power: 40, accuracy: 100, pp: 15, type: '草', category: 'special', effect: { drain: 0.5 }, description: '吸取大量HP' },
  '生长': { name: '生长', power: 0, accuracy: 100, pp: 20, type: '一般', category: 'status', effect: { statBoost: '特攻', amount: 1 }, description: '身体成长' },
  '变硬': { name: '变硬', power: 0, accuracy: 100, pp: 30, type: '一般', category: 'status', effect: { statBoost: '防御', amount: 1 }, description: '身体变硬' },
  '滚动': { name: '滚动', power: 30, accuracy: 90, pp: 20, type: '岩石', category: 'physical', effect: { powerDoublesEachTurn: true }, description: '滚动攻击' },
  '尖石攻击': { name: '尖石攻击', power: 100, accuracy: 80, pp: 5, type: '岩石', category: 'physical', effect: null, description: '尖石攻击' },
  '双针': { name: '双针', power: 25, accuracy: 100, pp: 20, type: '虫', category: 'physical', effect: { hits: 2, chance: 0.3, status: 'poison' }, description: '双针刺' },
  '飞弹针': { name: '飞弹针', power: 25, accuracy: 95, pp: 20, type: '虫', category: 'physical', effect: { hits: 'random', maxHits: 5 }, description: '飞弹针' },
  '致命针刺': { name: '致命针刺', power: 50, accuracy: 100, pp: 25, type: '虫', category: 'physical', effect: null, description: '致命针刺' },
  '麻痹粉': { name: '麻痹粉', power: 0, accuracy: 75, pp: 35, type: '草', category: 'status', effect: { status: 'paralysis' }, description: '撒麻痹粉' },
  '毒粉': { name: '毒粉', power: 0, accuracy: 75, pp: 35, type: '毒', category: 'status', effect: { status: 'poison' }, description: '撒毒粉' },
  '睡眠粉': { name: '睡眠粉', power: 0, accuracy: 75, pp: 15, type: '草', category: 'status', effect: { status: 'sleep' }, description: '撒睡眠粉' },
  '虫咬': { name: '虫咬', power: 60, accuracy: 100, pp: 20, type: '虫', category: 'physical', effect: null, description: '虫咬' },
  '吐丝': { name: '吐丝', power: 0, accuracy: 95, pp: 40, type: '虫', category: 'status', effect: { statDrop: '速度', amount: 1 }, description: '吐丝缠住' },
  '虫鸣': { name: '虫鸣', power: 90, accuracy: 100, pp: 10, type: '虫', category: 'special', effect: { chance: 0.1, statDrop: '特防', amount: 1 }, description: '虫鸣声攻击' },
  '追击': { name: '追击', power: 40, accuracy: 100, pp: 20, type: '恶', category: 'physical', effect: null, description: '追击' },
  '黑色目光': { name: '黑色目光', power: 0, accuracy: 100, pp: 5, type: '一般', category: 'status', effect: { preventsEscape: true }, description: '黑色目光阻止逃跑' },
  '毒烟': { name: '毒烟', power: 0, accuracy: 100, pp: 20, type: '毒', category: 'status', effect: { chance: 0.5, status: 'poison' }, description: '释放毒烟' },
  '吼叫': { name: '吼叫', power: 0, accuracy: 100, pp: 20, type: '一般', category: 'status', effect: { statDrop: '攻击', amount: 1 }, description: '吼叫威吓' },
  '舍身冲撞': { name: '舍身冲撞', power: 120, accuracy: 100, pp: 15, type: '一般', category: 'physical', effect: { recoil: 0.33 }, description: '舍身撞击' },
  '超音波': { name: '超音波', power: 0, accuracy: 55, pp: 20, type: '一般', category: 'status', effect: { status: 'confusion' }, description: '超音波' },
  '高速星星': { name: '高速星星', power: 60, accuracy: 100, pp: 20, type: '一般', category: 'special', effect: { alwaysHits: true }, description: '高速星星' },
  '空气刃': { name: '空气刃', power: 60, accuracy: 95, pp: 25, type: '飞行', category: 'special', effect: { criticalRate: 1 }, description: '空气刃' },
  '飞翔': { name: '飞翔', power: 90, accuracy: 95, pp: 15, type: '飞行', category: 'physical', effect: { chargeTurn: true }, description: '飞翔攻击' },
  '钢翼': { name: '钢翼', power: 70, accuracy: 90, pp: 25, type: '钢', category: 'physical', effect: { chance: 0.3, statBoost: '防御', amount: 1 }, description: '钢翼' },
  '神鸟猛击': { name: '神鸟猛击', power: 140, accuracy: 90, pp: 5, type: '飞行', category: 'physical', effect: { recoil: 0.5 }, description: '神鸟猛击' },
  '影子球': { name: '影子球', power: 80, accuracy: 100, pp: 15, type: '幽灵', category: 'special', effect: { chance: 0.2, statDrop: '特防', amount: 1 }, description: '影子球' },
  '咬咬': { name: '咬咬', power: 60, accuracy: 100, pp: 25, type: '恶', category: 'physical', effect: { chance: 0.3, flinch: true }, description: '咬咬' },
  '愤怒': { name: '愤怒', power: 20, accuracy: 100, pp: 20, type: '一般', category: 'physical', effect: { boostsWithDamage: true }, description: '愤怒' },
  '电光一闪': { name: '电光一闪', power: 40, accuracy: 100, pp: 30, type: '一般', category: 'physical', effect: { priority: 1 }, description: '电光一闪' },
  '必杀门牙': { name: '必杀门牙', power: 80, accuracy: 90, pp: 15, type: '一般', category: 'physical', effect: { chance: 0.1, flinch: true }, description: '必杀门牙' },
  '疯狂乱抓': { name: '疯狂乱抓', power: 18, accuracy: 80, pp: 15, type: '一般', category: 'physical', effect: { hits: 'random', maxHits: 5 }, description: '疯狂乱抓' },
  '咬碎': { name: '咬碎', power: 80, accuracy: 100, pp: 15, type: '恶', category: 'physical', effect: { chance: 0.2, statDrop: '防御', amount: 1 }, description: '咬碎' },
  '吸取': { name: '吸取', power: 20, accuracy: 100, pp: 25, type: '草', category: 'special', effect: { drain: 0.5 }, description: '吸取HP' },
  '寄生种子': { name: '寄生种子', power: 0, accuracy: 90, pp: 10, type: '草', category: 'status', effect: { leechSeed: true }, description: '寄生种子' },
  '毒液冲击': { name: '毒液冲击', power: 65, accuracy: 100, pp: 10, type: '毒', category: 'special', effect: null, description: '毒液冲击' },
  '污泥炸弹': { name: '污泥炸弹', power: 90, accuracy: 100, pp: 10, type: '毒', category: 'special', effect: { chance: 0.3, statDrop: '特防', amount: 1 }, description: '污泥炸弹' },
  '剧毒': { name: '剧毒', power: 0, accuracy: 90, pp: 10, type: '毒', category: 'status', effect: { status: 'badPoison' }, description: '剧毒' },
  '毒针': { name: '毒针', power: 15, accuracy: 100, pp: 35, type: '毒', category: 'physical', effect: { chance: 0.3, status: 'poison' }, description: '毒针' },
  '毒牙': { name: '毒牙', power: 50, accuracy: 100, pp: 25, type: '毒', category: 'physical', effect: { chance: 0.2, status: 'poison' }, description: '毒牙' },
  '毒尾': { name: '毒尾', power: 50, accuracy: 100, pp: 25, type: '毒', category: 'physical', effect: { chance: 0.1, status: 'poison' }, description: '毒尾' },
  '翅膀攻击': { name: '翅膀攻击', power: 60, accuracy: 100, pp: 35, type: '飞行', category: 'physical', effect: null, description: '翅膀攻击' },
  '空气切割': { name: '空气切割', power: 75, accuracy: 95, pp: 15, type: '飞行', category: 'special', effect: { chance: 0.3, flinch: true }, description: '空气切割' },
  '勇鸟猛攻': { name: '勇鸟猛攻', power: 120, accuracy: 100, pp: 15, type: '飞行', category: 'physical', effect: { recoil: 0.33 }, description: '勇鸟猛攻' },
  '啄': { name: '啄', power: 35, accuracy: 100, pp: 35, type: '飞行', category: 'physical', effect: null, description: '啄' },
  '撞击': { name: '撞击', power: 40, accuracy: 100, pp: 35, type: '一般', category: 'physical', effect: null, description: '撞击' },
  '冲击': { name: '冲击', power: 50, accuracy: 100, pp: 35, type: '一般', category: 'physical', effect: null, description: '冲击' },
  '抓': { name: '抓', power: 40, accuracy: 100, pp: 35, type: '一般', category: 'physical', effect: null, description: '抓' },
  '拍打': { name: '拍打', power: 40, accuracy: 100, pp: 35, type: '一般', category: 'physical', effect: null, description: '拍打' },
  '叫声': { name: '叫声', power: 0, accuracy: 100, pp: 40, type: '一般', category: 'status', effect: { statDrop: '攻击', amount: 1 }, description: '叫声' },
  '摇尾巴': { name: '摇尾巴', power: 0, accuracy: 100, pp: 30, type: '一般', category: 'status', effect: { statDrop: '防御', amount: 1 }, description: '摇尾巴' },
  '瞪眼': { name: '瞪眼', power: 0, accuracy: 100, pp: 30, type: '一般', category: 'status', effect: { statDrop: '防御', amount: 1 }, description: '瞪眼' },
  '聚气': { name: '聚气', power: 0, accuracy: 100, pp: 30, type: '一般', category: 'status', effect: { statBoost: '命中', amount: 1 }, description: '聚气' },
  '变硬': { name: '变硬', power: 0, accuracy: 100, pp: 30, type: '一般', category: 'status', effect: { statBoost: '防御', amount: 1 }, description: '变硬' },
  '防御卷曲': { name: '防御卷曲', power: 0, accuracy: 100, pp: 40, type: '一般', category: 'status', effect: { statBoost: '防御', amount: 1 }, description: '防御卷曲' },
  '剑舞': { name: '剑舞', power: 0, accuracy: 100, pp: 20, type: '一般', category: 'status', effect: { statBoost: '攻击', amount: 2 }, description: '剑舞' },
  '变圆': { name: '变圆', power: 0, accuracy: 100, pp: 40, type: '一般', category: 'status', effect: { statBoost: '防御', amount: 1 }, description: '变圆' },
  '高速移动': { name: '高速移动', power: 0, accuracy: 100, pp: 30, type: '超能力', category: 'status', effect: { statBoost: '速度', amount: 2 }, description: '高速移动' },
  '唱歌': { name: '唱歌', power: 0, accuracy: 55, pp: 15, type: '一般', category: 'status', effect: { status: 'sleep' }, description: '唱歌' },
  '打鼾': { name: '打鼾', power: 50, accuracy: 100, pp: 15, type: '一般', category: 'special', effect: { chance: 0.3, flinch: true }, description: '打鼾' },
  '睡觉': { name: '睡觉', power: 0, accuracy: 100, pp: 10, type: '超能力', category: 'status', effect: { heal: 1.0, status: 'sleep', turns: 2 }, description: '睡觉' },
  '打盹': { name: '打盹', power: 0, accuracy: 100, pp: 10, type: '超能力', category: 'status', effect: { heal: 0.5, status: 'sleep' }, description: '打盹' },
  '治愈之愿': { name: '治愈之愿', power: 0, accuracy: 100, pp: 10, type: '一般', category: 'status', effect: { heal: 1.0, faintUser: true }, description: '治愈之愿' },
  '光合作用': { name: '光合作用', power: 0, accuracy: 100, pp: 5, type: '草', category: 'status', effect: { heal: 0.5 }, description: '光合作用' },
  '晨光': { name: '晨光', power: 0, accuracy: 100, pp: 5, type: '一般', category: 'status', effect: { heal: 0.5 }, description: '晨光' },
  '破坏死光': { name: '破坏死光', power: 150, accuracy: 90, pp: 5, type: '一般', category: 'special', effect: { rechargeTurn: true }, description: '破坏死光' },
  '百万吨重拳': { name: '百万吨重拳', power: 80, accuracy: 85, pp: 20, type: '一般', category: 'physical', effect: null, description: '百万吨重拳' },
  '百万吨重踢': { name: '百万吨重踢', power: 120, accuracy: 75, pp: 5, type: '一般', category: 'physical', effect: null, description: '百万吨重踢' },
  '泰山压顶': { name: '泰山压顶', power: 85, accuracy: 100, pp: 15, type: '一般', category: 'physical', effect: null, description: '泰山压顶' },
  '舍身冲撞': { name: '舍身冲撞', power: 120, accuracy: 100, pp: 15, type: '一般', category: 'physical', effect: { recoil: 0.33 }, description: '舍身冲撞' },
  '三角攻击': { name: '三角攻击', power: 80, accuracy: 100, pp: 10, type: '一般', category: 'special', effect: null, description: '三角攻击' },
  '撕裂爪': { name: '撕裂爪', power: 75, accuracy: 95, pp: 10, type: '一般', category: 'physical', effect: { criticalRate: 1 }, description: '撕裂爪' },
  '连斩': { name: '连斩', power: 40, accuracy: 95, pp: 20, type: '一般', category: 'physical', effect: { hitsConsecutive: true }, description: '连斩' },
  '居合斩': { name: '居合斩', power: 50, accuracy: 95, pp: 30, type: '一般', category: 'physical', effect: { criticalRate: 1 }, description: '居合斩' },
  '劈开': { name: '劈开', power: 70, accuracy: 100, pp: 20, type: '一般', category: 'physical', effect: null, description: '劈开' },
  '头槌': { name: '头槌', power: 70, accuracy: 100, pp: 15, type: '一般', category: 'physical', effect: { chance: 0.3, flinch: true }, description: '头槌' },
  '角撞': { name: '角撞', power: 65, accuracy: 100, pp: 25, type: '一般', category: 'physical', effect: { chance: 0.3, flinch: true }, description: '角撞' },
  '猛撞': { name: '猛撞', power: 90, accuracy: 85, pp: 20, type: '一般', category: 'physical', effect: { chance: 0.3, flinch: true }, description: '猛撞' },
  '甜气': { name: '甜气', power: 0, accuracy: 100, pp: 20, type: '一般', category: 'status', effect: { statDrop: '闪避', amount: 2 }, description: '甜气' },
  '舔': { name: '舔', power: 30, accuracy: 100, pp: 30, type: '幽灵', category: 'physical', effect: { chance: 0.3, status: 'paralysis' }, description: '舔' },
  '咬': { name: '咬', power: 60, accuracy: 100, pp: 25, type: '恶', category: 'physical', effect: { chance: 0.3, flinch: true }, description: '咬' },
  '吼': { name: '吼', power: 0, accuracy: 100, pp: 20, type: '一般', category: 'status', effect: { statDrop: '攻击', amount: 1 }, description: '吼' },
  '聚宝功': { name: '聚宝功', power: 40, accuracy: 100, pp: 20, type: '一般', category: 'physical', effect: null, description: '聚宝功' },
  '火焰牙': { name: '火焰牙', power: 65, accuracy: 95, pp: 15, type: '火', category: 'physical', effect: { chance: 0.1, status: 'burn' }, description: '火焰牙' },
  '冰冻牙': { name: '冰冻牙', power: 65, accuracy: 95, pp: 15, type: '冰', category: 'physical', effect: { chance: 0.1, status: 'freeze' }, description: '冰冻牙' },
  '雷电牙': { name: '雷电牙', power: 65, accuracy: 95, pp: 15, type: '电', category: 'physical', effect: { chance: 0.1, status: 'paralysis' }, description: '雷电牙' },
  '溶解液': { name: '溶解液', power: 40, accuracy: 100, pp: 30, type: '毒', category: 'special', effect: { chance: 0.3, statDrop: '特防', amount: 1 }, description: '溶解液' },
  '酸液炸弹': { name: '酸液炸弹', power: 40, accuracy: 100, pp: 20, type: '毒', category: 'special', effect: { chance: 0.1, statDrop: '特防', amount: 2 }, description: '酸液炸弹' },
  '火花': { name: '火花', power: 40, accuracy: 100, pp: 25, type: '火', category: 'special', effect: { chance: 0.1, status: 'burn' }, description: '火花' },
  '火焰弹': { name: '火焰弹', power: 65, accuracy: 100, pp: 15, type: '火', category: 'special', effect: { chance: 0.1, status: 'burn' }, description: '火焰弹' },
  '喷射火焰': { name: '喷射火焰', power: 90, accuracy: 100, pp: 15, type: '火', category: 'special', effect: { chance: 0.1, status: 'burn' }, description: '喷射火焰' },
  '大字爆炎': { name: '大字爆炎', power: 110, accuracy: 85, pp: 5, type: '火', category: 'special', effect: { chance: 0.1, status: 'burn' }, description: '大字爆炎' },
  '火焰拳': { name: '火焰拳', power: 75, accuracy: 100, pp: 15, type: '火', category: 'physical', effect: { chance: 0.1, status: 'burn' }, description: '火焰拳' },
  '火焰轮': { name: '火焰轮', power: 60, accuracy: 100, pp: 25, type: '火', category: 'physical', effect: { chance: 0.1, status: 'burn' }, description: '火焰轮' },
  '烈焰冲锋': { name: '烈焰冲锋', power: 120, accuracy: 100, pp: 15, type: '火', category: 'physical', effect: { chance: 0.1, status: 'burn', recoil: 0.33 }, description: '烈焰冲锋' },
  '烟幕': { name: '烟幕', power: 0, accuracy: 100, pp: 20, type: '火', category: 'status', effect: { statDrop: '命中', amount: 1 }, description: '烟幕' },
  '烈暴风': { name: '烈暴风', power: 40, accuracy: 100, pp: 25, type: '飞行', category: 'special', effect: null, description: '烈暴风' },
  '龙卷风': { name: '龙卷风', power: 40, accuracy: 100, pp: 20, type: '龙', category: 'special', effect: { chance: 0.2, flinch: true }, description: '龙卷风' },
  '龙息': { name: '龙息', power: 60, accuracy: 100, pp: 20, type: '龙', category: 'special', effect: { chance: 0.3, status: 'paralysis' }, description: '龙息' },
  '龙爪': { name: '龙爪', power: 80, accuracy: 100, pp: 15, type: '龙', category: 'physical', effect: null, description: '龙爪' },
  '龙之怒': { name: '龙之怒', power: 0, accuracy: 100, pp: 10, type: '龙', category: 'special', effect: { fixedDamage: 40 }, description: '龙之怒' },
  '水枪': { name: '水枪', power: 40, accuracy: 100, pp: 25, type: '水', category: 'special', effect: null, description: '水枪' },
  '泡沫光线': { name: '泡沫光线', power: 65, accuracy: 100, pp: 20, type: '水', category: 'special', effect: { chance: 0.3, statDrop: '速度', amount: 1 }, description: '泡沫光线' },
  '冲浪': { name: '冲浪', power: 90, accuracy: 100, pp: 15, type: '水', category: 'special', effect: null, description: '冲浪' },
  '水炮': { name: '水炮', power: 110, accuracy: 80, pp: 5, type: '水', category: 'special', effect: null, description: '水炮' },
  '潜水': { name: '潜水', power: 80, accuracy: 100, pp: 10, type: '水', category: 'physical', effect: { chargeTurn: true }, description: '潜水' },
  '冰冻光束': { name: '冰冻光束', power: 90, accuracy: 100, pp: 10, type: '冰', category: 'special', effect: { chance: 0.1, status: 'freeze' }, description: '冰冻光束' },
  '冰冻之风': { name: '冰冻之风', power: 55, accuracy: 95, pp: 15, type: '冰', category: 'special', effect: { chance: 1.0, statDrop: '速度', amount: 1 }, description: '冰冻之风' },
  '暴风雪': { name: '暴风雪', power: 110, accuracy: 70, pp: 5, type: '冰', category: 'special', effect: { chance: 0.1, status: 'freeze' }, description: '暴风雪' },
  '急冻光线': { name: '急冻光线', power: 90, accuracy: 100, pp: 10, type: '冰', category: 'special', effect: { chance: 0.1, status: 'freeze' }, description: '急冻光线' },
  '急冻拳': { name: '急冻拳', power: 75, accuracy: 100, pp: 15, type: '冰', category: 'physical', effect: { chance: 0.1, status: 'freeze' }, description: '急冻拳' },
  '电击': { name: '电击', power: 40, accuracy: 100, pp: 30, type: '电', category: 'special', effect: { chance: 0.1, status: 'paralysis' }, description: '电击' },
  '十万伏特': { name: '十万伏特', power: 90, accuracy: 100, pp: 15, type: '电', category: 'special', effect: { chance: 0.1, status: 'paralysis' }, description: '十万伏特' },
  '打雷': { name: '打雷', power: 110, accuracy: 70, pp: 10, type: '电', category: 'special', effect: { chance: 0.3, status: 'paralysis' }, description: '打雷' },
  '雷电': { name: '雷电', power: 110, accuracy: 70, pp: 10, type: '电', category: 'special', effect: { chance: 0.3, status: 'paralysis' }, description: '雷电' },
  '雷电拳': { name: '雷电拳', power: 75, accuracy: 100, pp: 15, type: '电', category: 'physical', effect: { chance: 0.1, status: 'paralysis' }, description: '雷电拳' },
  '电磁波': { name: '电磁波', power: 0, accuracy: 90, pp: 20, type: '电', category: 'status', effect: { status: 'paralysis' }, description: '电磁波' },
  '充电': { name: '充电', power: 0, accuracy: 100, pp: 20, type: '电', category: 'status', effect: { statBoost: '特防', amount: 1 }, description: '充电' },
  '放电': { name: '放电', power: 80, accuracy: 100, pp: 15, type: '电', category: 'special', effect: { chance: 0.3, status: 'paralysis' }, description: '放电' },
  '藤鞭': { name: '藤鞭', power: 45, accuracy: 100, pp: 25, type: '草', category: 'physical', effect: null, description: '藤鞭' },
  '飞叶快刀': { name: '飞叶快刀', power: 55, accuracy: 95, pp: 25, type: '草', category: 'physical', effect: { criticalRate: 1 }, description: '飞叶快刀' },
  '叶刃': { name: '叶刃', power: 90, accuracy: 100, pp: 10, type: '草', category: 'physical', effect: { criticalRate: 1 }, description: '叶刃' },
  '日光束': { name: '日光束', power: 120, accuracy: 100, pp: 10, type: '草', category: 'special', effect: { chargeTurn: true }, description: '日光束' },
  '能量球': { name: '能量球', power: 80, accuracy: 100, pp: 10, type: '草', category: 'special', effect: { chance: 0.1, statDrop: '特防', amount: 1 }, description: '能量球' },
  '种子机关枪': { name: '种子机关枪', power: 25, accuracy: 100, pp: 30, type: '草', category: 'physical', effect: { hits: 'random', maxHits: 5 }, description: '种子机关枪' },
  '强力鞭打': { name: '强力鞭打', power: 120, accuracy: 85, pp: 10, type: '草', category: 'physical', effect: null, description: '强力鞭打' },
  '花瓣舞': { name: '花瓣舞', power: 120, accuracy: 100, pp: 10, type: '草', category: 'special', effect: { multiTurn: 3, confusionAfter: true }, description: '花瓣舞' },
  '精神强念': { name: '精神强念', power: 90, accuracy: 100, pp: 10, type: '超能力', category: 'special', effect: { chance: 0.1, statDrop: '特防', amount: 1 }, description: '精神强念' },
  '念力': { name: '念力', power: 50, accuracy: 100, pp: 25, type: '超能力', category: 'special', effect: { chance: 0.3, flinch: true }, description: '念力' },
  '瞬间移动': { name: '瞬间移动', power: 0, accuracy: 100, pp: 20, type: '超能力', category: 'status', effect: { teleport: true }, description: '瞬间移动' },
  '铁壁': { name: '铁壁', power: 0, accuracy: 100, pp: 15, type: '钢', category: 'status', effect: { statBoost: '防御', amount: 2 }, description: '铁壁' },
  '硬撑': { name: '硬撑', power: 70, accuracy: 100, pp: 20, type: '一般', category: 'physical', effect: null, description: '硬撑' },
  '撒娇': { name: '撒娇', power: 0, accuracy: 100, pp: 20, type: '妖精', category: 'status', effect: { statDrop: '攻击', amount: 2 }, description: '撒娇' },
  '迷人': { name: '迷人', power: 0, accuracy: 100, pp: 15, type: '一般', category: 'status', effect: { attract: true }, description: '迷人' },
  '魅惑之声': { name: '魅惑之声', power: 40, accuracy: 100, pp: 15, type: '妖精', category: 'special', effect: null, description: '魅惑之声' },
  '魔法闪耀': { name: '魔法闪耀', power: 80, accuracy: 100, pp: 10, type: '妖精', category: 'special', effect: null, description: '魔法闪耀' },
  '幻象光': { name: '幻象光', power: 65, accuracy: 100, pp: 20, type: '超能力', category: 'special', effect: { chance: 0.1, status: 'confusion' }, description: '幻象光' },
  '精神冲击': { name: '精神冲击', power: 80, accuracy: 100, pp: 10, type: '超能力', category: 'special', effect: null, description: '精神冲击' },
  '模仿': { name: '模仿', power: 0, accuracy: 100, pp: 10, type: '一般', category: 'status', effect: { mimic: true }, description: '模仿' },
  '挥指': { name: '挥指', power: 0, accuracy: 100, pp: 10, type: '一般', category: 'status', effect: { metronome: true }, description: '挥指' },
  '滚动': { name: '滚动', power: 30, accuracy: 90, pp: 20, type: '岩石', category: 'physical', effect: { powerDoublesEachTurn: true }, description: '滚动' },
  '岩石打磨': { name: '岩石打磨', power: 0, accuracy: 100, pp: 20, type: '岩石', category: 'status', effect: { statBoost: '攻击', amount: 1, statBoost2: '速度', amount: 1 }, description: '岩石打磨' },
  '尖石攻击': { name: '尖石攻击', power: 100, accuracy: 80, pp: 5, type: '岩石', category: 'physical', effect: null, description: '尖石攻击' },
  '地球上投': { name: '地球上投', power: 0, accuracy: 100, pp: 20, type: '格斗', category: 'physical', effect: { damageByLevel: true }, description: '地球上投' },
  '劲力': { name: '劲力', power: 80, accuracy: 100, pp: 15, type: '格斗', category: 'physical', effect: { chance: 0.3, statDrop: '防御', amount: 1 }, description: '劲力' },
  '十字切': { name: '十字切', power: 100, accuracy: 80, pp: 5, type: '格斗', category: 'physical', effect: { criticalRate: 1 }, description: '十字切' },
  '臂锤': { name: '臂锤', power: 100, accuracy: 90, pp: 10, type: '格斗', category: 'physical', effect: { statDrop: '速度', amount: 1 }, description: '臂锤' },
  '空手劈': { name: '空手劈', power: 50, accuracy: 100, pp: 25, type: '格斗', category: 'physical', effect: null, description: '空手劈' },
  '劈瓦': { name: '劈瓦', power: 75, accuracy: 100, pp: 15, type: '格斗', category: 'physical', effect: null, description: '劈瓦' },
  '健美': { name: '健美', power: 0, accuracy: 100, pp: 15, type: '格斗', category: 'status', effect: { statBoost: '攻击', amount: 1, statBoost2: '防御', amount: 1 }, description: '健美' },
  '集中猛击': { name: '集中猛击', power: 100, accuracy: 100, pp: 5, type: '格斗', category: 'physical', effect: { requiresFocus: true }, description: '集中猛击' },
  '火箭头槌': { name: '火箭头槌', power: 130, accuracy: 100, pp: 10, type: '一般', category: 'physical', effect: { recoil: 0.33 }, description: '火箭头槌' },
  '冲撞': { name: '冲撞', power: 90, accuracy: 85, pp: 20, type: '一般', category: 'physical', effect: { chance: 0.3, flinch: true }, description: '冲撞' },
  '践踏': { name: '践踏', power: 65, accuracy: 100, pp: 20, type: '一般', category: 'physical', effect: { chance: 0.3, flinch: true }, description: '践踏' },
  '飞踢': { name: '飞踢', power: 100, accuracy: 95, pp: 10, type: '格斗', category: 'physical', effect: { missRecoil: true }, description: '飞踢' },
  '弹跳': { name: '弹跳', power: 85, accuracy: 85, pp: 10, type: '飞行', category: 'physical', effect: { jumpTurn: true }, description: '弹跳' },
  '飞膝踢': { name: '飞膝踢', power: 130, accuracy: 90, pp: 10, type: '格斗', category: 'physical', effect: { missRecoil: true }, description: '飞膝踢' },
  '毒击': { name: '毒击', power: 80, accuracy: 100, pp: 20, type: '毒', category: 'physical', effect: { chance: 0.3, status: 'poison' }, description: '毒击' },
  '臭泥爆弹': { name: '臭泥爆弹', power: 90, accuracy: 100, pp: 10, type: '毒', category: 'special', effect: { chance: 0.3, statDrop: '特防', amount: 1 }, description: '臭泥爆弹' },
  '垃圾射击': { name: '垃圾射击', power: 120, accuracy: 80, pp: 5, type: '毒', category: 'physical', effect: { chance: 0.3, statDrop: '防御', amount: 1 }, description: '垃圾射击' },
  '暗影爪': { name: '暗影爪', power: 70, accuracy: 100, pp: 15, type: '幽灵', category: 'physical', effect: { criticalRate: 1 }, description: '暗影爪' },
  '暗袭要害': { name: '暗袭要害', power: 70, accuracy: 100, pp: 15, type: '恶', category: 'physical', effect: { criticalRate: 1, ignoresProtect: true }, description: '暗袭要害' },
  '欺诈': { name: '欺诈', power: 95, accuracy: 100, pp: 15, type: '恶', category: 'special', effect: { usesTargetAttack: true }, description: '欺诈' },
  '突袭': { name: '突袭', power: 80, accuracy: 100, pp: 5, type: '恶', category: 'physical', effect: { priority: 1, onlyIfFaster: true }, description: '突袭' },
  '猛闪': { name: '猛闪', power: 60, accuracy: 100, pp: 20, type: '一般', category: 'physical', effect: null, description: '猛闪' },
  '热风': { name: '热风', power: 95, accuracy: 90, pp: 10, type: '火', category: 'special', effect: { chance: 0.1, statDrop: '特防', amount: 1 }, description: '热风' },
  '水溅跃': { name: '水溅跃', power: 0, accuracy: 100, pp: 40, type: '水', category: 'status', effect: null, description: '水溅跃' },
  '泡沫': { name: '泡沫', power: 40, accuracy: 100, pp: 30, type: '水', category: 'special', effect: { chance: 0.1, statDrop: '速度', amount: 1 }, description: '泡沫' },
  '热水': { name: '热水', power: 80, accuracy: 100, pp: 10, type: '水', category: 'special', effect: { chance: 0.2, status: 'burn' }, description: '热水' },
  '水流喷射': { name: '水流喷射', power: 40, accuracy: 100, pp: 20, type: '水', category: 'special', effect: { priority: 1 }, description: '水流喷射' },
  '帮助': { name: '帮助', power: 0, accuracy: 100, pp: 20, type: '一般', category: 'status', effect: null, description: '帮助' },
  '燃烧殆尽': { name: '燃烧殆尽', power: 130, accuracy: 100, pp: 5, type: '火', category: 'special', effect: null, description: '燃烧殆尽' },
  '超级角击': { name: '超级角击', power: 120, accuracy: 85, pp: 10, type: '一般', category: 'physical', effect: null, description: '超级角击' },
  '龙之舞': { name: '龙之舞', power: 0, accuracy: 100, pp: 20, type: '龙', category: 'status', effect: { statBoost: '攻击', amount: 1, statBoost2: '速度', amount: 1 }, description: '龙之舞' },
  '鳞片噪音': { name: '鳞片噪音', power: 0, accuracy: 100, pp: 40, type: '一般', category: 'status', effect: { statBoost: '防御', amount: 1 }, description: '抖动鳞片' }
}

module.exports = MOVE_DATABASE
